import { Roboto } from "next/font/google";
import "./globals.css";

const RobotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500', '700'],
  display: 'swap'
});

export const metadata = {
  title: "Gwendy Wendell - Rocket Coding Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${RobotoSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
